FROM python:3.12-slim

WORKDIR /app
ADD . /app
RUN pip install -r requirements.txt && \
    chmod +x ./entry.sh

ENV GUNICORN_WORKERS=2
ENV GUNICORN_KEEPALIVE=15
ENV GUNICORN_TIMEOUT=30
ENV GUNICORN_MAX_REQUESTS=2000
ENV GUNICORN_MAX_REQUESTS_JITTER=200
ENV GUNICORN_REAL_IP_HEADER=""

ENV EPM_WINDOW_WIDTH=240
ENV EPM_WINDOW_HEIGHT=240
ENV EPM_SEARCH_PAGE_AMOUNT_PER_PAGE=5

ENV REDIS_HOST=127.0.0.1
ENV REDIS_PORT=6379
ENV REDIS_PASSWORD=""
ENV REDIS_USERNAME=""

ENV PIXIV_ACCESS_TOKEN=""
ENV PIXIV_REFRESH_TOKEN=""
ENV PIXIV_EXPIRE_IN=3600
ENV PIXIV_WEB_COOKIES=""
ENV PIXIV_WEB_UID=""
ENV PIXIV_SENTRY_TRACE=""

ENV BAIDU_TRANSLATE_APPID=""
ENV BAIDU_TRANSLATE_SECRET=""

ENV AI_TRANSLATOR="gemini"

ENV GEMINI_API_KEY=""

ENV CF_ACCOUNT_ID=""
ENV CF_API_TOKEN=""
ENV CF_MODEL="@cf/qwen/qwen2.5-coder-32b-instruct"

EXPOSE 5025

VOLUME ["/app/log", "/app/cache"]

HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
    CMD python3 /app/health_check.py || exit 1

LABEL maintainer="AXOLOTLTECH <s@saobby.com>"
LABEL description="在老人机的浏览器上访问 Pixiv"
LABEL version="1.0"

CMD ["bash", "/app/entry.sh"]
